fix some grammatical & punctuation errors in chapter 3
ivanporty/cloud-docker-k8s-book pull request #25
Opened 2023-09-16 18:12 UTC by naumov-andrey

2023-10-12 18:26 UTC, ivanporty approved these changes
Спасибо Андрей!

2023-10-12 18:27 UTC, ivanporty requested changes
Уберите FIXME пожалуйста

2023-10-15 02:26 UTC, naumov-andrey commented
FIXME убрал ✅

2023-10-24 20:02 UTC, ivanporty approved these changes

2023-10-24 20:02 UTC, merged